- name: Update brew
  shell: brew update && brew upgrade
  tags:
    - updates

- name: Install zsh
  homebrew: name=zsh

- name: Install Node
  homebrew:
    name: ["nodejs", "npm"]

- name: Install ohmyzsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  tags:
    - zsh

- name: Change shells
  shell: chsh
  tags:
    - zsh
- name: Install lazygit
  homebrew: name=lazygit

- name: Install Tmux
  homebrew: name=tmux

- name: Install neovim
  homebrew: name=neovim

- name: Install ripgrep
  homebrew: name=ripgrep

- name: Install Hammerspoon
  homebrew:
    name: hammerspoon
    state: present
    install_options: cask

- name: Install docker
  homebrew: name=docker

- name: Install git
  homebrew: name=git
