#!/usr/bin/env bash

# set -x
#
# # ====== Variables =============================
# declare -A gaps
# declare -A color
#
# gaps["top"]="4"
# gaps["bottom"]="24"
# gaps["left"]="4"
# gaps["right"]="4"
# gaps["inner"]="4"
#
# color["focused"]="0xE0808080"
# color["normal"]="0x00010101"
# color["preselect"]="0xE02d74da"
#
# # Uncomment to refresh ubersicht widget on workspace change
# # Make sure to replace WIDGET NAME for the name of the ubersicht widget
# #ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"
#
# # ===== Loading Scripting Additions ============
#
# # See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#
# # ===== Tiling setting =========================
#
# yabai -m config layout                      bsp
#
# yabai -m config top_padding                 "${gaps["top"]}"
# yabai -m config bottom_padding              "${gaps["bottom"]}"
# yabai -m config left_padding                "${gaps["left"]}"
# yabai -m config right_padding               "${gaps["right"]}"
# yabai -m config window_gap                  "${gaps["inner"]}"
#
# yabai -m config mouse_follows_focus         off
# yabai -m config focus_follows_mouse         off
#
# yabai -m config window_topmost              off
# yabai -m config window_opacity              off
# yabai -m config window_shadow               float
#
# yabai -m config window_border               on
# yabai -m config window_border_width         2
# yabai -m config active_window_border_color  "${color["focused"]}"
# yabai -m config normal_window_border_color  "${color["normal"]}"
# yabai -m config insert_feedback_color       "${color["preselect"]}"
#
# yabai -m config active_window_opacity       1.0
# yabai -m config normal_window_opacity       0.90
# yabai -m config split_ratio                 0.50
#
# yabai -m config auto_balance                off
#
# yabai -m config mouse_modifier              fn
# yabai -m config mouse_action1               move
# yabai -m config mouse_action2               resize
#
# # ===== Rules ==================================
#
# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
# yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
# yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
# yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
# yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="mpv" app="^mpv$" manage=off
# yabai -m rule --add label="Software Update" title="Software Update" manage=off
# yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
#
# # ===== Signals ================================
#
# yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
# yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"
#
# set +x
# printf "yabai: configuration loaded...\\n"
#
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# opens a new space or moves to a created space already
# yabai -m space --create && index="$(yabai -m query --spaces --display | jq 'map(select(."is-native-fullscreen" == false))[-1].index')" && yabai -m window --space "${index}" && yabai -m space --focus "${index}"
#
# navigate between spaces

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
# yabai -m space 1 --label 'I'
# yabai -m space 2 --label 'II'
# yabai -m space 3 --label 'III'
# yabai -m space 4 --label 'IV'
# yabai -m space 5 --label 'V'
# yabai -m space 6 --label 'VI'
# yabai -m space 7 --label 'VII'
# yabai -m space 8 --label 'VIII'
# yabai -m space 9 --label 'IX'
# yabai -m space 10 --label 'X'
